input {
  beats {
    port => 5044
  }
}

filter {
  if [log_source] == "suricata" {
    json {
      source => "message"
    }
    mutate {
      rename => { "[src_ip]" => "[attacker][ip]" }
      rename => { "[alert][signature]" => "[alert][signature]" }
    }
  }

  else if [log_source] == "modsecurity" {
    json {
      source => "message"
    }
    if [transaction][client_ip] {
      mutate {
        add_field => { "[attacker][ip]" => "%{[transaction][client_ip]}" }
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "waf-suricata-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
